pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: dotnet
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command:
    - cat
    tty: true
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                container('dotnet') {
                    sh 'dotnet --version'
                    sh 'dotnet restore'
                    sh 'dotnet build'
                }
            }
        }
    }
}
