pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:24
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
    }
  }
  environment {
    IMAGE_NAME = "registry.somepharm.local/SimpleWebApi:${BUILD_NUMBER}"
  }
  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('docker') {
          sh '''
            docker build -t $IMAGE_NAME .
            docker push $IMAGE_NAME
          '''
        }
      }
    }
  }
}
